import Image from 'next/image'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Pogoda dziś',
    description: 'Generated by someone',
}

const Weather = () => {
    const weatherData = [
        { type: 'Słonecznie', image: '/sunny.jpg' },
        { type: 'Deszczowo', image: '/rainy.jpg' },
        { type: 'Pochmurno', image: '/cloudy.jpg' },
        { type: 'Błyskawice', image: '/stormy.jpg' },
        { type: 'Mgła', image: '/foggy.jpg' },
    ]

    const randomWeather = () => {
        const randomIndex = Math.floor(Math.random() * weatherData.length)
        return randomIndex
    }

    let index = randomWeather()

    return (
        <div>
            <main className="flex flex-col items-center">
                <h1 className="text-3xl font-semibold m-2">Prognoza pogody</h1>
                <Button className="m-2">
                    <Link href="/">Przejdź do stony głównej</Link>
                </Button>
                <div className="flex flex-col items-center">
                    <h2 className="text-3xl m-2">{weatherData[index].type}</h2>
                    <Image
                        src={weatherData[index].image}
                        alt={weatherData[index].type}
                        width={600}
                        height={400}
                        className="m-2"
                    />
                </div>
            </main>
        </div>
    )
}

export default Weather
