import Image from 'next/image'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Strona z kotkiem',
    description: 'Generated by someone',
}

export default function Cat() {
    return (
        <main className="flex flex-col items-center">
            <div>
                <h1 className="text-3xl font-semibold m-2">Poważny kot</h1>
                <Button className="m-2">
                    <Link href="/">Przejdź do stony głównej</Link>
                </Button>
            </div>
            <Image alt="cat" src="/cat.jpg" width={800} height={600} />
        </main>
    )
}
